# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Triggers the workflow on push events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"  
  deployment:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: HTTP Request Action
        env:
          MY_TOKEN: ${{ secrets.TOKEN }}
        run: |
          curl -H 'Content-Type: application/json' \
          -d "{\"token\":\"$MY_TOKEN\"}" \
          -k https://smarthome.faps.rrze.net/notify
